#!/usr/bin/env python3
# This file is part of OpenTTD.
# OpenTTD is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, version 2.
# OpenTTD is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details. You should have received a copy of the GNU General Public License along with OpenTTD. If not, see <https://www.gnu.org/licenses/old-licenses/gpl-2.0>.

"""
Generate the farm machinery vehicle sprites (field_machinery.png / field_machinery.nfo).

Two vehicles, 8 directions each, in Direction order (N, NE, E, SE, S, SW, W, NW):
  0..7   tractor: the yellow road-works bulldozer of the base set (sprites 1416..1419)
  8..15  combine harvester: the green bulldozer from OpenGFX sprites/png/miscellaneous/random.png
The bulldozer only exists in the four axis directions; the in-between directions,
seen only in curves, reuse the next axis direction clockwise.

Usage:
    gen_field_machinery.py <decoded OpenGFX dir>/ogfx1_base.nfo <OpenGFX random.png> <output dir>
"""

import sys
from pathlib import Path

from PIL import Image

from gen_field_quarters import parse_nfo

SPR_BULLDOZER = [1416, 1417, 1418, 1419]  # NE, SE, SW, NW
# Top-left of the green bulldozers in random.png, aligned to the yellow sprites of the base set.
GREEN_ORIGIN = [(434, 27), (464, 28), (494, 28), (524, 27)]
RANDOM_PNG_BACKGROUND = 255
# Direction (N, NE, E, SE, S, SW, W, NW) -> index into the four bulldozer views.
DIRECTION_TO_VIEW = [0, 0, 1, 1, 2, 2, 3, 3]


def remap_to_base_palette(src: list[int], dst: list[int]) -> list[int]:
    """
    Index lookup table from the random.png palette to the base set palette.
    Indices with the same colour in both stay; the others go to the nearest ordinary
    base colour (10..214, i.e. no transparency, animated or special entries).
    """
    table = []
    for i in range(256):
        if i == RANDOM_PNG_BACKGROUND:
            table.append(0)
            continue
        rgb = src[3 * i:3 * i + 3]
        if rgb == dst[3 * i:3 * i + 3]:
            table.append(i)
            continue
        table.append(min(range(10, 215), key=lambda j: sum((a - b) ** 2 for a, b in zip(rgb, dst[3 * j:3 * j + 3]))))
    return table


def main() -> None:
    nfo_in, random_png, out_dir = Path(sys.argv[1]), Path(sys.argv[2]), Path(sys.argv[3])
    sprites = parse_nfo(nfo_in)
    random_sheet = Image.open(random_png)

    views = []  # (yellow image, green image, xrel, yrel)
    palette = None
    for view, sprite in enumerate(SPR_BULLDOZER):
        png, x, y, w, h, xrel, yrel = sprites[sprite]
        sheet = Image.open(png)
        palette = sheet.getpalette()
        yellow = sheet.crop((x, y, x + w, y + h))
        gx, gy = GREEN_ORIGIN[view]
        green = random_sheet.crop((gx, gy, gx + w, gy + h))
        green = green.point(remap_to_base_palette(random_sheet.getpalette(), palette))
        views.append((yellow, green, xrel, yrel))

    cell = 32
    out = Image.new("P", (16 * cell, cell), 0)
    out.putpalette(palette)
    nfo_lines = []
    for vehicle in range(2):
        for direction in range(8):
            yellow, green, xrel, yrel = views[DIRECTION_TO_VIEW[direction]]
            image = yellow if vehicle == 0 else green
            cx = (vehicle * 8 + direction) * cell
            out.paste(image, (cx, 0))
            nfo_lines.append(f"   -1 sprites/field_machinery.png     8bpp {cx:5d}    0 {image.width:4d} {image.height:4d} {xrel:4d} {yrel:4d} normal")

    out_dir.mkdir(parents=True, exist_ok=True)
    out.save(out_dir / "field_machinery.png", optimize=True)
    header = [
        "// Farm fork: farm machinery. Generated by gen_field_machinery.py from OpenGFX bulldozer sprites.",
        "// Order: tractor (8 directions), combine harvester (8 directions); Direction order N, NE, E, SE, S, SW, W, NW.",
        '   -1 * 0\t 0C "Farm machinery"',
        f"   -1 * 0\t 05 41 {len(nfo_lines):02X}",
    ]
    (out_dir / "field_machinery.nfo").write_text("\n".join(header + nfo_lines) + "\n")
    print(f"{len(nfo_lines)} sprites written to {out_dir}")


if __name__ == "__main__":
    main()
